#!/usr/bin/env bash

set -euo pipefail

DEFAULT_MAX_AGE=60

function main() {

    local rootDevice
    rootDevice=$(mount | grep -F 'on / type' | awk '{print $1}')
    local maxAlterInTagen="$1"

    ensure_root_permissions
    ensure_btrfs "${rootDevice}"

    local mountDir
    mountDir="$(mktemp -d)"
    local snapshots="${mountDir}/@snapshots"
    sudo mount -o subvolid=0 "${rootDevice}" "${mountDir}"

    ensure_snapshots_subvolume "$snapshots"
    local newSnapshotsRoot
    newSnapshotsRoot="${snapshots}/$(date +%Y-%m-%d_%H:%M:%S)"

    remove_old_snapshots "${maxAlterInTagen}" "${snapshots}"
    create_snapshots "${mountDir}" "${newSnapshotsRoot}"

    sudo umount "${mountDir}"
    rmdir "${mountDir}"

}

function parse_args() {
    maxAlterInTagen=${DEFAULT_MAX_AGE}
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -h | --help)
                print_usage
                exit 0
                ;;
            --max-age)
                maxAlterInTagen="$2"
                shift
                ;;
            *)
                echo "Unbekannte Option '$1'. Abbruch." >&2
                exit 1
                ;;
        esac
        shift
    done
}

function print_usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h|--help] [--max-age <AGE>]

Script description here.

Available options:

-h, --help      Print this help and exit
--max-age       Maximum age of snapshots in days. Defaults to ${DEFAULT_MAX_AGE}.
EOF

}

function ensure_root_permissions() {
    if ! sudo -v; then
        echo Unverzichtbare Rootrechte sind nicht verfügbar. Abbruch! >&2
        exit 1
    fi
}

function ensure_btrfs() {
    local rootDevice="$1"
    # Wenn das Dateisystem auf $rootDevice nicht BtrFS ist, sind Schnappschüsse
    # nicht möglich. Dies wird hier geprüft. Ggf. wird das Skript hier
    # verlassen.
    #
    # Um das snapshot-Skript auch auf nicht-BtrFS-Systemen im distup-Alias
    # verwenden zu können, ist der Exit-Code trotzdem "0".
    if [[ $(lsblk -no FSTYPE "${rootDevice}") != "btrfs" ]]; then
        echo Gerät "${rootDevice}" ist kein BtrFS-Dateisystem. Es wird kein Snapshot gemacht! >&2
        exit 0
    fi
}

function ensure_snapshots_subvolume() {
    local snapshots="$1"
    if ! [[ -d "$snapshots" ]]; then
        sudo btrfs subvol create "$snapshots"
    fi

    if ! sudo btrfs subvolume show "$snapshots" &>/dev/null; then
        echo "Verzeichnis für Snapshots existiert, aber ist kein BtrFS-Subvolume. Fahre trotzdem fort." >&2
    fi
}

function remove_old_snapshots() {
    # Lösche alle Snapshots, die älter sind als $maxTage Tage.
    local maxTage="$1"
    local snapshots="$2"
    local threshold
    threshold=$(date --date "${maxTage} days ago" +%s)

    local -A dateDirs=()
    local -a toDelete=()

    local curSnapshot
    while IFS= read -r -d '' curSnapshot; do
        local dateDir dirDate whenCreated
        dateDir="$(dirname "${curSnapshot}")"
        dirDate="$(basename "${dateDir}")"
        whenCreated="$(date +%s -d "${dirDate/_/ }")"
        if [[ "${whenCreated}" -le "${threshold}" ]]; then
            toDelete+=("${curSnapshot}")
            dateDirs["${dateDir}"]=1
        fi
    done < <(find "${snapshots}" -mindepth 2 -maxdepth 2 -print0)

    if [[ ${#toDelete[@]} -gt 0 ]]; then
        printf '%s\0' "${toDelete[@]}" |
            xargs -0 sudo btrfs subvolume delete --commit-after |
            sed "s!${mountDir}/!!g"
    fi

    if [[ ${#dateDirs[@]} -gt 0 ]]; then
        printf '%s\0' "${!dateDirs[@]}" | xargs -0 sudo rmdir
    fi
}

function create_snapshots() {
    # neue Snapshots anlegen
    local mountDir="${1}"
    local dest="${2}"
    sudo mkdir "${dest}"
    local srcSubvol
    sudo btrfs subvolume list "${mountDir}" |
        grep -Ev '/|@snapshots' |
        cut -d' ' -f9 |
        while read -r srcSubvol; do
            sudo btrfs subvolume "snapshot" -r "${mountDir}/${srcSubvol}" "${dest}/${srcSubvol}" |
                sed "s!${mountDir}/!!g"
        done
}

parse_args "$@"
main "${maxAlterInTagen}"
